services:
  solo-crm-db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solo_crm
    ports:
      - "5432:5432"
    volumes:
      - solo_crm_postgres:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - realtime_redis:/data

volumes:
  solo_crm_postgres:
  realtime_redis:
