import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, MessageSquare, RefreshCw, Send, ShieldCheck } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { Skeleton } from '@/components/ui/Skeleton';
import { cn } from '@/lib/cn';

const STATUSES=['open','in_progress','waiting_for_user','resolved','closed','reopened'];
const PRIORITIES=['low','medium','high'];

export default function AdminSupportTicketDetailPage(){
  const {ticketId}=useParams();const nav=useNavigate();const qc=useQueryClient();const [reply,setReply]=useState('');const [internal,setInternal]=useState(false);const [status,setStatus]=useState('');const [priority,setPriority]=useState('');const [resolutionNotes,setResolutionNotes]=useState('');const [error,setError]=useState('');
  const q=useQuery<any>({queryKey:['admin-support-ticket',ticketId],enabled:Boolean(ticketId),queryFn:()=>apiClient.get(`/admin/support/${ticketId}`).then(r=>r.data)});
  const refresh=()=>{qc.invalidateQueries({queryKey:['admin-support-ticket',ticketId]});qc.invalidateQueries({queryKey:['admin-support']})};
  const update=useMutation({mutationFn:(payload:any)=>apiClient.patch(`/support/${ticketId}/status`,payload),onSuccess:()=>{setError('');refresh()},onError:(e:any)=>setError(e?.response?.data?.message||'Ticket update failed.')});
  const message=useMutation({mutationFn:(payload:any)=>apiClient.post(`/support/${ticketId}/messages`,payload),onSuccess:()=>{setReply('');setInternal(false);setError('');refresh()},onError:(e:any)=>setError(e?.response?.data?.message||'Reply could not be sent.')});
  if(q.isLoading)return <div className="space-y-3">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-20"/>)}</div>;
  if(q.isError||!q.data?.ticket)return <ErrorState title="Support ticket could not load" message="The ticket may not exist or the API is unavailable." onRetry={()=>q.refetch()}/>;
  const t=q.data.ticket;const requester=t.patient||t.doctor||t.agent;
  return <div className="space-y-6"><header><button onClick={()=>nav('/admin/support')} className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-neutral-600"><ArrowLeft className="h-4 w-4"/>Support</button><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">{t.ticketId||'Support ticket'}</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{t.subject}</h1><p className="mt-1 text-sm text-neutral-500">{t.category.replace(/_/g,' ')} · {t.userType} · opened {new Date(t.createdAt).toLocaleString()}</p></div><button onClick={()=>q.refetch()} className="inline-flex min-h-11 items-center gap-2 self-start rounded-lg border bg-white px-4 text-sm font-semibold"><RefreshCw className={cn('h-4 w-4',q.isFetching&&'animate-spin')}/>Refresh</button></div></header>
  {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
  <div className="grid gap-5 xl:grid-cols-[1.5fr_.8fr]"><section className="rounded-xl border bg-white p-5"><div className="flex items-center gap-2"><MessageSquare className="h-5 w-5 text-neutral-500"/><h2 className="font-bold">Conversation</h2></div>{t.description&&<div className="mt-4 rounded-xl border bg-neutral-50 p-4 text-sm text-neutral-700">{t.description}</div>}<div className="mt-5 space-y-3">{t.messages?.length?t.messages.map((m:any)=><div key={m._id} className={cn('rounded-xl border p-4',m.senderRole==='admin'?'ml-6 bg-primary-50':'mr-6 bg-white',m.isInternal&&'border-amber-200 bg-amber-50')}><div className="flex justify-between gap-3"><strong className="text-sm">{m.senderRole==='admin'?'Admin':requester?.fullName||m.senderRole}{m.isInternal?' · Internal note':''}</strong><span className="text-xs text-neutral-500">{new Date(m.createdAt).toLocaleString()}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-neutral-700">{m.message}</p>{m.attachment&&<a href={m.attachment} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-semibold text-primary-700">View attachment</a>}</div>):<p className="text-sm text-neutral-500">No conversation messages yet.</p>}</div><div className="mt-5 border-t pt-5"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={4} placeholder="Write a reply or internal note…" className="w-full rounded-lg border px-3 py-2 text-sm"/><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="flex items-center gap-2 text-sm text-neutral-600"><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/>Internal note only</label><button disabled={!reply.trim()||message.isPending} onClick={()=>message.mutate({message:reply.trim(),isInternal:internal})} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white disabled:opacity-50"><Send className="h-4 w-4"/>{message.isPending?'Sending…':internal?'Add internal note':'Send reply'}</button></div></div></section>
  <aside className="space-y-5"><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Requester</h2><dl className="mt-4 space-y-3 text-sm">{[['Name',requester?.fullName],['ID',requester?.patientId||requester?.doctorId||requester?.agentId],['Mobile',requester?.mobile],['Email',requester?.email],['Clinic',requester?.clinicName]].map(([a,b])=><div key={a}><dt className="text-xs font-semibold uppercase text-neutral-500">{a}</dt><dd className="mt-1 font-medium">{b||'—'}</dd></div>)}</dl></section><section className="rounded-xl border bg-white p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-neutral-500"/><h2 className="font-bold">Triage & resolution</h2></div><div className="mt-4 space-y-4"><label className="block"><span className="text-xs font-semibold uppercase text-neutral-500">Status</span><select value={status||t.status} onChange={e=>setStatus(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3 text-sm">{STATUSES.map(x=><option key={x} value={x}>{x.replace(/_/g,' ')}</option>)}</select></label><label className="block"><span className="text-xs font-semibold uppercase text-neutral-500">Priority</span><select value={priority||t.priority} onChange={e=>setPriority(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3 text-sm">{PRIORITIES.map(x=><option key={x}>{x}</option>)}</select></label><label className="block"><span className="text-xs font-semibold uppercase text-neutral-500">Resolution notes</span><textarea value={resolutionNotes} onChange={e=>setResolutionNotes(e.target.value)} rows={4} placeholder={t.resolutionNotes||'Add resolution notes'} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"/></label><button disabled={update.isPending} onClick={()=>update.mutate({status:status||t.status,priority:priority||t.priority,...(resolutionNotes.trim()?{resolutionNotes:resolutionNotes.trim()}:{})})} className="min-h-11 w-full rounded-lg bg-neutral-900 px-4 text-sm font-semibold text-white">{update.isPending?'Saving…':'Save ticket state'}</button></div>{t.resolutionNotes&&<div className="mt-4 rounded-lg border bg-neutral-50 p-3 text-sm text-neutral-700"><strong>Current resolution notes</strong><p className="mt-1 whitespace-pre-wrap">{t.resolutionNotes}</p></div>}</section><section className="rounded-xl border bg-white p-5 text-sm"><h2 className="font-bold">Operational timestamps</h2><dl className="mt-3 space-y-2 text-neutral-600"><div>Last response: <strong>{t.lastResponseAt?new Date(t.lastResponseAt).toLocaleString():'—'}</strong></div><div>Closed: <strong>{t.closedAt?new Date(t.closedAt).toLocaleString():'—'}</strong></div><div>Assigned to: <strong>{t.assignedTo?.email||t.assignedTo?.mobile||'Unassigned'}</strong></div></dl></section></aside></div></div>
}
