import { useDeferredValue, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, Headphones, RefreshCw, RotateCcw } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { SearchInput } from '@/components/ui/SearchInput';
import { Skeleton } from '@/components/ui/Skeleton';
import { cn } from '@/lib/cn';

type Ticket={_id:string;ticketId?:string;userType:'patient'|'doctor'|'agent';category:string;subject:string;description?:string;priority:'low'|'medium'|'high';status:string;updatedAt:string;createdAt:string;patient?:any;doctor?:any;agent?:any;assignedTo?:any;lastResponseAt?:string};
type Response={items:Ticket[];meta:{page:number;limit:number;total:number;totalPages:number};summary:{total:number;open:number;inProgress:number;waitingForUser:number;resolved:number;closed:number;reopened:number}};
const CATEGORIES=['payment','video_access','program','refund','fee_share','withdrawal','qr_code','profile','technical'];
const STATUSES=['open','in_progress','waiting_for_user','resolved','closed','reopened'];

export default function AdminSupportPage(){
  const nav=useNavigate();const [search,setSearch]=useState('');const dq=useDeferredValue(search.trim());const [status,setStatus]=useState('');const [priority,setPriority]=useState('');const [category,setCategory]=useState('');const [userType,setUserType]=useState('');const [page,setPage]=useState(1);
  const q=useQuery<Response>({queryKey:['admin-support',page,dq,status,priority,category,userType],queryFn:()=>apiClient.get('/admin/support',{params:{page,limit:20,...(dq?{search:dq}:{}),...(status?{status}:{}),...(priority?{priority}:{}),...(category?{category}:{}),...(userType?{userType}:{})}}).then(r=>r.data)});
  const s=q.data?.summary;
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">Operations</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Support Tickets</h1><p className="mt-1 text-sm text-neutral-500">Triage patient, doctor and agent issues from one operational queue.</p></div><button onClick={()=>q.refetch()} className="inline-flex min-h-11 items-center gap-2 self-start rounded-lg border bg-white px-4 text-sm font-semibold"><RefreshCw className={cn('h-4 w-4',q.isFetching&&'animate-spin')}/>Refresh</button></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[Headphones,'Total',s?.total],[Clock3,'Open + in progress',(s?.open??0)+(s?.inProgress??0)],[RotateCcw,'Waiting / reopened',(s?.waitingForUser??0)+(s?.reopened??0)],[CheckCircle2,'Resolved',s?.resolved]].map(([I,l,v]:any)=><div key={l} className="rounded-xl border bg-white p-4"><I className="h-5 w-5 text-neutral-500"/><p className="mt-3 text-xs font-semibold uppercase text-neutral-500">{l}</p><p className="mt-1 text-2xl font-bold">{v??'—'}</p></div>)}</section>
  <section className="overflow-hidden rounded-xl border bg-white"><div className="grid gap-3 border-b p-4 xl:grid-cols-[1fr_155px_145px_165px_145px]"><SearchInput value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="Ticket ID, subject or description"/><Filter value={status} onChange={v=>{setStatus(v);setPage(1)}} options={STATUSES} label="All statuses"/><Filter value={priority} onChange={v=>{setPriority(v);setPage(1)}} options={['low','medium','high']} label="All priorities"/><Filter value={category} onChange={v=>{setCategory(v);setPage(1)}} options={CATEGORIES} label="All categories"/><Filter value={userType} onChange={v=>{setUserType(v);setPage(1)}} options={['patient','doctor','agent']} label="All users"/></div>
  {q.isError?<div className="p-5"><ErrorState title="Support tickets could not load" message="Check the API and retry." onRetry={()=>q.refetch()}/></div>:q.isLoading?<div className="space-y-3 p-5">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-16"/>)}</div>:!q.data?.items.length?<div className="p-12 text-center text-sm text-neutral-500">No support tickets match the current filters.</div>:<><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase text-neutral-500"><tr><th className="px-5 py-3">Ticket</th><th className="px-4 py-3">Requester</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Updated</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{q.data.items.map(t=>{const r=t.patient||t.doctor||t.agent;return <tr key={t._id}><td className="px-5 py-4"><div className="font-semibold">{t.ticketId||t._id}</div><div className="mt-1 max-w-[320px] truncate text-xs text-neutral-500">{t.subject}</div></td><td className="px-4 py-4"><div className="font-semibold">{r?.fullName||'—'}</div><div className="text-xs text-neutral-500">{r?.patientId||r?.doctorId||r?.agentId||t.userType}</div></td><td className="px-4 py-4">{t.category.replace(/_/g,' ')}</td><td className="px-4 py-4"><span className={cn('rounded-full px-2.5 py-1 text-xs font-semibold',t.priority==='high'?'bg-red-50 text-red-700':t.priority==='medium'?'bg-amber-50 text-amber-700':'bg-neutral-100 text-neutral-700')}>{t.priority}</span></td><td className="px-4 py-4"><span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-semibold">{t.status.replace(/_/g,' ')}</span></td><td className="px-4 py-4 text-neutral-600">{new Date(t.updatedAt).toLocaleString()}</td><td className="px-5 py-4 text-right"><button onClick={()=>nav(`/admin/support/${t._id}`)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Open</button></td></tr>})}</tbody></table></div><div className="flex flex-col gap-3 border-t px-5 py-3 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-neutral-500">Page {q.data.meta.page} of {q.data.meta.totalPages} · {q.data.meta.total} tickets</p><div className="flex gap-2"><button type="button" disabled={page<=1} onClick={()=>setPage(v=>Math.max(1,v-1))} className="inline-flex h-9 w-9 items-center justify-center rounded-lg border disabled:opacity-40" aria-label="Previous page"><ChevronLeft className="h-4 w-4"/></button><button type="button" disabled={page>=q.data.meta.totalPages} onClick={()=>setPage(v=>v+1)} className="inline-flex h-9 w-9 items-center justify-center rounded-lg border disabled:opacity-40" aria-label="Next page"><ChevronRight className="h-4 w-4"/></button></div></div></>}</section></div>}
function Filter({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:string[];label:string}){return <select value={value} onChange={e=>onChange(e.target.value)} className="min-h-11 rounded-lg border px-3 text-sm"><option value="">{label}</option>{options.map(x=><option key={x} value={x}>{x.replace(/_/g,' ')}</option>)}</select>}
