import { useQuery } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, CircleDollarSign, RefreshCw, RotateCcw, ShieldAlert } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { Skeleton } from '@/components/ui/Skeleton';
import { formatCurrency } from '@/lib/formatters';
import { cn } from '@/lib/cn';

const money=(value?:number)=>value==null?'—':formatCurrency(value);
export default function AdminRefundDetailPage(){
  const {refundId=''}=useParams(); const navigate=useNavigate();
  const query=useQuery<any>({queryKey:['admin-refund',refundId],enabled:Boolean(refundId),queryFn:()=>apiClient.get(`/admin/refunds/${refundId}`).then(r=>r.data)});
  if(query.isLoading)return <div className="space-y-4">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-20 w-full"/>)}</div>;
  if(query.isError||!query.data)return <ErrorState title="Refund could not load" message="The refund may not exist or the admin API is unavailable." onRetry={()=>query.refetch()}/>;
  const {refund:r,integrity}=query.data;
  return <div className="space-y-6"><header><button onClick={()=>navigate('/admin/refunds')} className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-neutral-600"><ArrowLeft className="h-4 w-4"/>Refunds</button><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">Refund review</p><h1 className="mt-2 text-2xl font-bold text-neutral-950">{r.gatewayRefundId||`Refund ${r._id.slice(-8)}`}</h1><p className="mt-1 text-sm text-neutral-500">{r.patient?.fullName||'Patient'} · {r.refundType?.replaceAll('_',' ')}</p></div><button onClick={()=>query.refetch()} className="inline-flex min-h-11 items-center gap-2 self-start rounded-lg border px-4 text-sm font-semibold"><RefreshCw className={cn('h-4 w-4',query.isFetching&&'animate-spin')}/>Refresh</button></div></header>
  <div className={cn('rounded-xl border px-4 py-3 text-sm',integrity.completed?'border-emerald-200 bg-emerald-50 text-emerald-900':'border-amber-200 bg-amber-50 text-amber-900')}><strong>Integrity:</strong> Payment {integrity.paymentWasVerified?'verified/refunded state':'not verified'} · Refund {integrity.completed?'completed':'not completed'} · Fee reversal {integrity.feeShareReversalRecorded?'recorded':'not recorded'}{integrity.feeShareAlreadyWithdrawn?' · Doctor share had already been withdrawn':''}</div>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[RotateCcw,'Refund amount',money(r.refundAmount)],[CircleDollarSign,'Fee-share reversal',money(r.feeShareReversal)],[CheckCircle2,'Status',r.status],[ShieldAlert,'Type',r.refundType?.replaceAll('_',' ')]].map(([Icon,label,value]:any)=><div key={label} className="rounded-xl border bg-white p-4"><Icon className="h-5 w-5 text-neutral-500"/><p className="mt-3 text-xs font-semibold uppercase tracking-wide text-neutral-500">{label}</p><p className="mt-1 text-lg font-bold capitalize">{value||'—'}</p></div>)}</section>
  <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Refund record</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[['Gateway refund ID',r.gatewayRefundId],['Status',r.status],['Type',r.refundType?.replaceAll('_',' ')],['Requested amount',money(r.refundAmount)],['Reason',r.reason],['Rejection reason',r.rejectionReason],['Processed by',r.processedBy?.email||r.processedBy?.mobile],['Processed at',r.processedAt?new Date(r.processedAt).toLocaleString():'—']].map(([a,b])=><div key={a}><dt className="text-xs font-semibold uppercase text-neutral-500">{a}</dt><dd className="mt-1 break-words font-medium">{b||'—'}</dd></div>)}</dl></section>
  <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Payment & order</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2">{[['Invoice',r.payment?.invoiceNumber],['Transaction',r.payment?.gatewayTransactionId],['Payment status',r.payment?.status],['Paid amount',money(r.payment?.paidAmount)],['Order',r.order?.orderId],['Order total',money(r.order?.finalAmount)],['Doctor share',money(r.payment?.doctorFeeShare)],['Platform share',money(r.payment?.platformShare)]].map(([a,b])=><div key={a}><dt className="text-xs font-semibold uppercase text-neutral-500">{a}</dt><dd className="mt-1 break-all font-medium">{b||'—'}</dd></div>)}</dl></section></div>
  <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Patient</h2><div className="mt-4 text-sm"><p className="font-semibold">{r.patient?.fullName||'—'}</p><p className="mt-1 text-neutral-500">{r.patient?.patientId||'—'} · {r.patient?.mobile||'—'}</p><p className="mt-1 text-neutral-500">Referral {r.patient?.referralLocked?'locked':'not locked'}</p></div></section><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Doctor & program</h2><div className="mt-4 text-sm"><p className="font-semibold">{r.doctor?.fullName||'—'}</p><p className="mt-1 text-neutral-500">{r.doctor?.doctorId||'—'} · {r.doctor?.clinicName||'—'}</p><p className="mt-3 font-medium">{r.payment?.program?.name||'Program —'}</p></div></section></div>
  <div className="rounded-xl border border-neutral-200 bg-neutral-50 px-4 py-3 text-sm text-neutral-600">This screen is intentionally read-only. The backend currently stores refund records but does not expose a safe admin approve/process/reject workflow, so the UI does not invent financial mutation actions.</div></div>;
}