import { useDeferredValue, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { CheckCircle2, ChevronLeft, ChevronRight, CreditCard, RefreshCw, RotateCcw, XCircle } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { SearchInput } from '@/components/ui/SearchInput';
import { Skeleton } from '@/components/ui/Skeleton';
import { formatCurrency } from '@/lib/formatters';
import { cn } from '@/lib/cn';

type Payment={_id:string;invoiceNumber?:string;gatewayTransactionId?:string;paidAmount?:number;refundAmount?:number;doctorFeeShare?:number;platformShare?:number;status:string;paymentMethod?:string;createdAt:string;patient?:{patientId?:string;fullName?:string;mobile?:string};doctor?:{doctorId?:string;fullName?:string};program?:{programCode?:string;name?:string};order?:{orderId?:string;status?:string}};
type Response={items:Payment[];meta:{page:number;limit:number;total:number;totalPages:number};summary:{total:number;verified:number;verifiedAmount:number;failed:number;refunded:number;refundAmount:number}};
const statuses=['successful','manually_verified','pending','failed','refunded','partially_refunded','disputed','chargeback','cancelled'];
const badge=(s:string)=>cn('rounded-full px-2.5 py-1 text-xs font-semibold', ['successful','manually_verified'].includes(s)?'bg-emerald-50 text-emerald-700':s==='failed'||s==='chargeback'?'bg-red-50 text-red-700':s.includes('refund')?'bg-amber-50 text-amber-700':'bg-neutral-100 text-neutral-700');
export default function AdminPaymentsPage(){
 const navigate=useNavigate(); const [search,setSearch]=useState(''); const q=useDeferredValue(search.trim()); const [status,setStatus]=useState(''); const [page,setPage]=useState(1);
 const query=useQuery<Response>({queryKey:['admin-payments',page,q,status],queryFn:()=>apiClient.get('/admin/payments',{params:{page,limit:20,...(q?{search:q}:{}),...(status?{status}:{})}}).then(r=>r.data)});
 const s=query.data?.summary;
 return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">Commerce</p><h1 className="mt-2 text-2xl font-bold text-neutral-950 sm:text-3xl">Payments</h1><p className="mt-1 text-sm text-neutral-500">Gateway payment ledger and verification trail. Program activation should follow a verified payment, never a pending attempt.</p></div><button onClick={()=>query.refetch()} className="inline-flex min-h-11 items-center gap-2 self-start rounded-lg border border-neutral-300 bg-white px-4 text-sm font-semibold"><RefreshCw className={cn('h-4 w-4',query.isFetching&&'animate-spin')}/>Refresh</button></header>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[CreditCard,'Total attempts',s?.total],[CheckCircle2,'Verified',s?.verified],[XCircle,'Failed',s?.failed],[RotateCcw,'Refunded',s?.refunded]].map(([Icon,label,value]:any)=><div key={label} className="rounded-xl border border-neutral-200 bg-white p-4"><div className="flex justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-neutral-500">{label}</p><p className="mt-2 text-2xl font-bold">{value??'—'}</p></div><Icon className="h-5 w-5 text-neutral-500"/></div></div>)}</section>
 {s&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><strong>Verified collection:</strong> {formatCurrency(s.verifiedAmount)}{s.refundAmount>0&&<> · Recorded refund amount: {formatCurrency(s.refundAmount)}</>}</div>}
 <section className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="flex flex-col gap-3 border-b border-neutral-200 p-4 sm:flex-row"><div className="flex-1"><SearchInput value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="Invoice, transaction ID or gateway order"/></div><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="min-h-11 rounded-lg border border-neutral-300 px-3 text-sm"><option value="">All statuses</option>{statuses.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></div>
 {query.isError?<div className="p-5"><ErrorState title="Payments could not load" message="Check the API and admin session, then retry." onRetry={()=>query.refetch()}/></div>:query.isLoading?<div className="space-y-3 p-5">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-14 w-full"/>)}</div>:!query.data?.items.length?<div className="p-12 text-center text-sm text-neutral-500">No payment attempts match these filters.</div>:<><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase tracking-wide text-neutral-500"><tr><th className="px-5 py-3">Payment</th><th className="px-4 py-3">Patient</th><th className="px-4 py-3">Program</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Method</th><th className="px-4 py-3">Status</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y divide-neutral-100">{query.data.items.map(p=><tr key={p._id} className="hover:bg-neutral-50"><td className="px-5 py-4"><div className="font-semibold text-neutral-950">{p.invoiceNumber||p.gatewayTransactionId||p._id.slice(-8)}</div><div className="mt-1 text-xs text-neutral-500">{p.order?.orderId||'Order —'} · {new Date(p.createdAt).toLocaleString()}</div></td><td className="px-4 py-4"><div className="font-medium">{p.patient?.fullName||'—'}</div><div className="text-xs text-neutral-500">{p.patient?.patientId||p.patient?.mobile||'—'}</div></td><td className="px-4 py-4"><div>{p.program?.name||'—'}</div><div className="text-xs text-neutral-500">{p.program?.programCode||''}</div></td><td className="px-4 py-4 font-semibold">{p.paidAmount==null?'—':formatCurrency(p.paidAmount)}</td><td className="px-4 py-4 text-neutral-600">{p.paymentMethod||'—'}</td><td className="px-4 py-4"><span className={badge(p.status)}>{p.status.replaceAll('_',' ')}</span></td><td className="px-5 py-4 text-right"><button onClick={()=>navigate(`/admin/payments/${p._id}`)} className="rounded-lg border border-neutral-200 px-3 py-2 text-xs font-semibold">View</button></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-neutral-200 px-5 py-3"><p className="text-xs text-neutral-500">Page {query.data.meta.page} of {Math.max(query.data.meta.totalPages,1)} · {query.data.meta.total} attempts</p><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(v=>Math.max(1,v-1))} className="h-9 w-9 rounded-lg border disabled:opacity-40"><ChevronLeft className="mx-auto h-4 w-4"/></button><button disabled={page>=query.data.meta.totalPages} onClick={()=>setPage(v=>v+1)} className="h-9 w-9 rounded-lg border disabled:opacity-40"><ChevronRight className="mx-auto h-4 w-4"/></button></div></div></>}
 </section></div>;
}