import { useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { AlertTriangle, ArrowLeft, ClipboardList, GitBranch, RefreshCw, Route } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { Skeleton } from '@/components/ui/Skeleton';
import { Modal } from '@/components/ui/Modal';
import { cn } from '@/lib/cn';

type ParentQuestion={_id:string;questionText:string;questionType:string;isActive?:boolean};
type Ref={_id:string;name?:string;code?:string;isActive?:boolean;bodyRegion?:string};
type Question={
  _id:string;questionText:string;questionTextHindi?:string;questionType:string;options?:{label?:string;labelHindi?:string;value?:string}[];
  scopeType?:'common'|'body_region'|'surgery_type';bodyRegion?:Ref|null;surgeryType?:Ref|null;
  isRedFlag:boolean;redFlagAnswerValues?:unknown[];redFlagOperator?:string;redFlagMinValue?:number;redFlagMaxValue?:number;redFlagSafetyMessage?:string;
  displayOrder:number;isActive:boolean;showIfQuestion?:ParentQuestion|null;showIfAnswer?:string;conditionalLogic?:{dependsOnQuestion?:ParentQuestion|null;operator?:string;value?:unknown;values?:unknown[];minValue?:number;maxValue?:number};createdAt?:string;updatedAt?:string;
};
type Pathways={bodyRegions:Array<{_id:string;name:string;isActive:boolean}>;surgeryTypes:Array<{_id:string;name:string;code:string;isActive:boolean;bodyRegion?:{_id:string;name:string}}>};
const QUESTION_TYPES=['single_choice','multiple_choice','yes_no','pain_scale','number','text','date','image'];
const typeLabel=(value?:string)=>value?value.replace(/_/g,' ').replace(/\b\w/g,(char)=>char.toUpperCase()):'—';
const dateText=(value?:string)=>value?new Date(value).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
const valuesText=(values?:unknown[])=>values?.length?values.map(String).join(', '):'—';
const scopeText=(q:Question)=>q.scopeType==='body_region'?`Body Region · ${q.bodyRegion?.name||'Unassigned'}`:q.scopeType==='surgery_type'?`Surgery Type · ${q.surgeryType?.name||'Unassigned'}`:'Common · All pathways';

function Card({title,children}:{title:string;children:ReactNode}){return <section className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="border-b border-neutral-100 bg-neutral-50/60 px-5 py-4"><h2 className="text-sm font-bold text-neutral-950">{title}</h2></div><div className="grid gap-4 p-5 sm:grid-cols-2">{children}</div></section>}
function Item({label,value}:{label:string;value:ReactNode}){return <div><div className="text-[11px] font-semibold uppercase tracking-wide text-neutral-400">{label}</div><div className="mt-1 break-words text-sm font-semibold text-neutral-900">{value}</div></div>}

export default function AdminAssessmentDetailPage(){
 const {assessmentId=''}=useParams();const navigate=useNavigate();const qc=useQueryClient();const [showEdit,setShowEdit]=useState(false);const [showStatus,setShowStatus]=useState(false);const [formError,setFormError]=useState('');
 const query=useQuery<Question>({queryKey:['admin-assessment-question',assessmentId],queryFn:()=>apiClient.get(`/admin/assessment-questions/${assessmentId}`).then(r=>r.data),enabled:Boolean(assessmentId)});
 const parentQuery=useQuery<{items:Question[]}>({queryKey:['assessment-parent-questions'],queryFn:()=>apiClient.get('/admin/assessment-questions',{params:{page:1,limit:100,status:'active',sortBy:'displayOrder',sortOrder:'asc'}}).then(r=>r.data)});
 const pathwaysQuery=useQuery<Pathways>({queryKey:['admin-assessment-pathways'],queryFn:()=>apiClient.get('/admin/assessment-pathways').then(r=>r.data)});
 const updateMutation=useMutation({mutationFn:(payload:Record<string,unknown>)=>apiClient.patch(`/admin/assessment-questions/${assessmentId}`,payload),onSuccess:()=>{setShowEdit(false);setFormError('');qc.invalidateQueries({queryKey:['admin-assessment-question',assessmentId]});qc.invalidateQueries({queryKey:['admin-assessment-questions']});qc.invalidateQueries({queryKey:['assessment-questions']});},onError:(error:any)=>setFormError(error?.response?.data?.message||'Question could not be updated.')});
 const statusMutation=useMutation({mutationFn:({active,reason}:{active:boolean;reason:string})=>apiClient.post(`/admin/assessment-questions/${assessmentId}/${active?'reactivate':'deactivate'}`,{reason}),onSuccess:()=>{setShowStatus(false);setFormError('');qc.invalidateQueries({queryKey:['admin-assessment-question',assessmentId]});qc.invalidateQueries({queryKey:['admin-assessment-questions']});qc.invalidateQueries({queryKey:['assessment-questions']});},onError:(error:any)=>setFormError(error?.response?.data?.message||'Status could not be changed.')});
 if(query.isLoading)return <div className="space-y-5"><Skeleton className="h-32 w-full"/><Skeleton className="h-28 w-full"/><Skeleton className="h-[420px] w-full"/></div>;
 if(query.isError||!query.data)return <ErrorState title="Assessment question could not load" message="Check the question ID and admin API connection, then retry." onRetry={()=>query.refetch()}/>;
 const question=query.data;const parent=question.conditionalLogic?.dependsOnQuestion||question.showIfQuestion;const conditional=Boolean(parent);
 return <div className="mx-auto w-full max-w-[1500px] space-y-5">
  <header className="rounded-2xl border border-neutral-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-5 xl:flex-row xl:items-start xl:justify-between"><div className="flex min-w-0 items-start gap-4"><button type="button" onClick={()=>navigate('/admin/assessments')} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-neutral-200 text-neutral-600"><ArrowLeft className="h-5 w-5"/></button><div className={cn('flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl',question.isRedFlag?'bg-rose-50 text-rose-700':'bg-primary-50 text-primary-700')}>{question.isRedFlag?<AlertTriangle className="h-7 w-7"/>:<ClipboardList className="h-7 w-7"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h1 className="max-w-4xl text-xl font-bold tracking-tight text-neutral-950 sm:text-2xl">{question.questionText}</h1><span className={cn('rounded-full px-2.5 py-1 text-xs font-semibold',question.isActive?'bg-emerald-50 text-emerald-700':'bg-neutral-100 text-neutral-600')}>{question.isActive?'Active':'Inactive'}</span>{question.isRedFlag&&<span className="rounded-full bg-rose-50 px-2.5 py-1 text-xs font-semibold text-rose-700">Red flag</span>}</div><p className="mt-2 text-sm text-neutral-600">{typeLabel(question.questionType)} · {scopeText(question)}</p><p className="mt-1 text-xs text-neutral-500">Updated {dateText(question.updatedAt)}</p></div></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>query.refetch()} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-neutral-300 px-3.5 text-sm font-semibold text-neutral-700"><RefreshCw className={cn('h-4 w-4',query.isFetching&&'animate-spin')}/>Refresh</button><button type="button" onClick={()=>setShowEdit(true)} className="inline-flex min-h-10 items-center rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white">Edit configuration</button></div></div></header>

  <section className="rounded-xl border border-primary-200 bg-primary-50 p-4"><div className="flex items-start gap-3"><Route className="mt-0.5 h-5 w-5 text-primary-700"/><div><div className="text-sm font-bold text-primary-950">Question scope: {scopeText(question)}</div><p className="mt-1 text-sm leading-6 text-primary-800">{question.scopeType==='body_region'?'This question appears after the patient selects this body region, in addition to common questions.':question.scopeType==='surgery_type'?'This question appears only when the patient selects this surgery, in addition to common and body-region questions.':'This question is shown in every clinical pathway unless conditional visibility hides it.'}</p></div></div></section>
  {question.isRedFlag&&<section className="rounded-xl border border-rose-200 bg-rose-50 p-4"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 text-rose-700"/><div><div className="text-sm font-bold text-rose-950">Safety-sensitive question</div><p className="mt-1 text-sm leading-6 text-rose-800">Matching answers send the assessment to Clinical Reviews and block programme selection until cleared.</p></div></div></section>}

  <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><main className="space-y-5">
   <Card title="Question content"><Item label="English" value={question.questionText}/><Item label="Hindi" value={question.questionTextHindi||'—'}/><Item label="Type" value={typeLabel(question.questionType)}/><Item label="Scope" value={scopeText(question)}/><Item label="Display order" value={String(question.displayOrder??0)}/><Item label="Status" value={question.isActive?'Active':'Inactive'}/></Card>
   <Card title="Answer configuration"><Item label="Options" value={question.options?.length?question.options.map((o)=>o.label||o.value).filter(Boolean).join(', '):'Not required / not configured'}/><Item label="Option count" value={String(question.options?.length||0)}/></Card>
   <Card title="Red-flag rule"><Item label="Enabled" value={question.isRedFlag?'Yes':'No'}/><Item label="Operator" value={typeLabel(question.redFlagOperator)}/><Item label="Trigger values" value={valuesText(question.redFlagAnswerValues)}/><Item label="Range" value={question.redFlagMinValue!==undefined||question.redFlagMaxValue!==undefined?`${question.redFlagMinValue??'—'} to ${question.redFlagMaxValue??'—'}`:'—'}/><Item label="Safety message" value={question.redFlagSafetyMessage||'—'}/></Card>
   <Card title="Conditional visibility"><Item label="Conditional" value={conditional?'Yes':'No'}/><Item label="Depends on" value={parent?.questionText||'Always shown'}/><Item label="Expected answer" value={question.showIfAnswer||(question.conditionalLogic?.value!==undefined?String(question.conditionalLogic.value):'—')}/><Item label="Operator" value={typeLabel(question.conditionalLogic?.operator||(conditional?'equals':undefined))}/></Card>
  </main><aside className="space-y-4 xl:sticky xl:top-5"><section className="overflow-hidden rounded-xl border border-neutral-200 bg-white"><div className="border-b border-neutral-100 bg-neutral-50/60 px-4 py-4"><h2 className="text-sm font-bold text-neutral-950">Configuration actions</h2><p className="mt-1 text-xs text-neutral-500">Deactivate instead of deleting so historical assessments stay explainable.</p></div><div className="space-y-2 p-4"><button type="button" onClick={()=>setShowEdit(true)} className="w-full rounded-xl border border-neutral-200 px-4 py-3 text-left text-sm font-semibold text-neutral-700">Edit question and scope</button><button type="button" onClick={()=>{setFormError('');setShowStatus(true)}} className={cn('w-full rounded-xl border px-4 py-3 text-left text-sm font-semibold',question.isActive?'border-rose-200 text-rose-700':'border-emerald-200 text-emerald-700')}>{question.isActive?'Deactivate question':'Reactivate question'}</button><button type="button" onClick={()=>navigate('/admin/risk-reviews')} className="flex w-full items-center gap-2 rounded-xl border border-neutral-200 px-4 py-3 text-left text-sm font-semibold text-neutral-700"><AlertTriangle className="h-4 w-4"/>Open Clinical Reviews</button></div></section><section className="rounded-xl border border-neutral-200 bg-white p-4"><div className="flex items-center gap-2 text-sm font-bold text-neutral-950"><GitBranch className="h-4 w-4 text-primary-700"/>Rule summary</div><div className="mt-4 space-y-3 text-sm"><Summary label="Scope" value={scopeText(question)}/><Summary label="Red flag" value={question.isRedFlag?'Yes':'No'}/><Summary label="Conditional" value={conditional?'Yes':'No'}/></div></section></aside></div>

  <Modal isOpen={showEdit} onClose={()=>{setShowEdit(false);setFormError('')}} title="Edit assessment question" size="xl"><EditQuestionForm question={question} parents={(parentQuery.data?.items||[]).filter((item)=>item._id!==question._id)} pathways={pathwaysQuery.data} saving={updateMutation.isPending} error={formError} onCancel={()=>{setShowEdit(false);setFormError('')}} onSubmit={(payload)=>updateMutation.mutate(payload)}/></Modal>
  <Modal isOpen={showStatus} onClose={()=>{setShowStatus(false);setFormError('')}} title={question.isActive?'Deactivate question':'Reactivate question'} size="md"><StatusForm active={question.isActive} saving={statusMutation.isPending} error={formError} onCancel={()=>setShowStatus(false)} onSubmit={(reason)=>statusMutation.mutate({active:!question.isActive,reason})}/></Modal>
 </div>;
}

function EditQuestionForm({question,parents,pathways,saving,error,onCancel,onSubmit}:{question:Question;parents:Question[];pathways?:Pathways;saving:boolean;error:string;onCancel:()=>void;onSubmit:(payload:Record<string,unknown>)=>void}){
 const [scopeType,setScopeType]=useState(question.scopeType||'common');const [bodyRegion,setBodyRegion]=useState(question.bodyRegion?._id||'');const [surgeryType,setSurgeryType]=useState(question.surgeryType?._id||'');
 const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);if(scopeType==='body_region'&&!bodyRegion)return;if(scopeType==='surgery_type'&&!surgeryType)return;const options=String(form.get('options')||'').split('\n').map((line)=>line.trim()).filter(Boolean).map((line)=>{const [label,value]=line.split('|').map((part)=>part.trim());return{label,value:value||label}});const isRedFlag=form.get('isRedFlag')==='on';const payload:Record<string,unknown>={questionText:String(form.get('questionText')||'').trim(),questionTextHindi:String(form.get('questionTextHindi')||'').trim(),questionType:form.get('questionType'),displayOrder:Number(form.get('displayOrder')||0),scopeType,bodyRegion:scopeType==='body_region'?bodyRegion:null,surgeryType:scopeType==='surgery_type'?surgeryType:null,isRedFlag,options,showIfQuestion:String(form.get('showIfQuestion')||'')||null,showIfAnswer:String(form.get('showIfAnswer')||'').trim()};if(isRedFlag){payload.redFlagOperator=form.get('redFlagOperator');payload.redFlagAnswerValues=String(form.get('redFlagAnswerValues')||'').split(',').map((v)=>v.trim()).filter(Boolean);payload.redFlagMinValue=form.get('redFlagMinValue')||undefined;payload.redFlagMaxValue=form.get('redFlagMaxValue')||undefined;payload.redFlagSafetyMessage=String(form.get('redFlagSafetyMessage')||'').trim()}onSubmit(payload)};
 return <form onSubmit={submit} className="space-y-6 pt-5">{error&&<div className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</div>}<div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className={fieldLabel}>Question text *</span><textarea name="questionText" required rows={3} defaultValue={question.questionText} className={textareaClass}/></label><label className="sm:col-span-2"><span className={fieldLabel}>Hindi text</span><textarea name="questionTextHindi" rows={2} defaultValue={question.questionTextHindi||''} className={textareaClass}/></label><label><span className={fieldLabel}>Type</span><select name="questionType" defaultValue={question.questionType} className={inputClass}>{QUESTION_TYPES.map((type)=><option key={type} value={type}>{typeLabel(type)}</option>)}</select></label><label><span className={fieldLabel}>Display order</span><input name="displayOrder" type="number" min="0" defaultValue={question.displayOrder} className={inputClass}/></label><label><span className={fieldLabel}>Scope</span><select value={scopeType} onChange={(e)=>{setScopeType(e.target.value as typeof scopeType);setBodyRegion('');setSurgeryType('')}} className={inputClass}><option value="common">Common</option><option value="body_region">Body Region</option><option value="surgery_type">Surgery Type</option></select></label>{scopeType==='body_region'?<label><span className={fieldLabel}>Body region *</span><select value={bodyRegion} onChange={(e)=>setBodyRegion(e.target.value)} required className={inputClass}><option value="">Select body region</option>{(pathways?.bodyRegions||[]).filter((i)=>i.isActive).map((i)=><option key={i._id} value={i._id}>{i.name}</option>)}</select></label>:scopeType==='surgery_type'?<label><span className={fieldLabel}>Surgery type *</span><select value={surgeryType} onChange={(e)=>setSurgeryType(e.target.value)} required className={inputClass}><option value="">Select surgery type</option>{(pathways?.surgeryTypes||[]).filter((i)=>i.isActive).map((i)=><option key={i._id} value={i._id}>{i.bodyRegion?.name?`${i.bodyRegion.name} — `:''}{i.name}</option>)}</select></label>:<div/>}<label className="sm:col-span-2"><span className={fieldLabel}>Options — one per line, optional value after |</span><textarea name="options" rows={5} defaultValue={(question.options||[]).map((o)=>`${o.label||o.value||''}${o.value&&o.value!==o.label?` | ${o.value}`:''}`).join('\n')} className={textareaClass}/></label></div>
 <section className="rounded-xl border border-neutral-200 p-4"><label className="flex items-center gap-3"><input name="isRedFlag" type="checkbox" defaultChecked={question.isRedFlag} className="h-4 w-4"/><span className="text-sm font-semibold text-neutral-700">Safety-sensitive / red-flag question</span></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label><span className={fieldLabel}>Operator</span><select name="redFlagOperator" defaultValue={question.redFlagOperator||'equals'} className={inputClass}>{['equals','not_equals','includes','gte','lte','between'].map((v)=><option key={v} value={v}>{typeLabel(v)}</option>)}</select></label><label><span className={fieldLabel}>Trigger values (comma-separated)</span><input name="redFlagAnswerValues" defaultValue={(question.redFlagAnswerValues||[]).join(', ')} className={inputClass}/></label><label><span className={fieldLabel}>Minimum</span><input name="redFlagMinValue" type="number" defaultValue={question.redFlagMinValue} className={inputClass}/></label><label><span className={fieldLabel}>Maximum</span><input name="redFlagMaxValue" type="number" defaultValue={question.redFlagMaxValue} className={inputClass}/></label><label className="sm:col-span-2"><span className={fieldLabel}>Safety message</span><textarea name="redFlagSafetyMessage" rows={2} defaultValue={question.redFlagSafetyMessage||''} className={textareaClass}/></label></div></section>
 <section className="rounded-xl border border-neutral-200 p-4"><h3 className="text-sm font-bold text-neutral-900">Conditional visibility</h3><div className="mt-3 grid gap-4 sm:grid-cols-2"><label><span className={fieldLabel}>Depends on question</span><select name="showIfQuestion" defaultValue={question.showIfQuestion?._id||question.conditionalLogic?.dependsOnQuestion?._id||''} className={inputClass}><option value="">Always shown</option>{parents.map((p)=><option key={p._id} value={p._id}>{p.questionText}</option>)}</select></label><label><span className={fieldLabel}>Expected answer</span><input name="showIfAnswer" defaultValue={question.showIfAnswer||String(question.conditionalLogic?.value??'')} className={inputClass}/></label></div></section>
 <div className="flex justify-end gap-2 border-t border-neutral-100 pt-5"><button type="button" onClick={onCancel} className="rounded-lg border border-neutral-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={saving} className="rounded-lg bg-primary-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Save changes'}</button></div></form>;
}

function StatusForm({active,saving,error,onCancel,onSubmit}:{active:boolean;saving:boolean;error:string;onCancel:()=>void;onSubmit:(reason:string)=>void}){const [reason,setReason]=useState('');return <div className="space-y-4 pt-4"><p className="text-sm text-neutral-600">{active?'This question will stop appearing in new assessments. Historical answers are preserved.':'This question will become available to new assessments using its configured scope.'}</p><textarea value={reason} onChange={(e)=>setReason(e.target.value)} rows={4} placeholder="Reason (required)" className={textareaClass}/>{error&&<div className="text-sm text-rose-700">{error}</div>}<div className="flex justify-end gap-2"><button onClick={onCancel} className="rounded-lg border border-neutral-300 px-4 py-2.5 text-sm font-semibold">Cancel</button><button disabled={!reason.trim()||saving} onClick={()=>onSubmit(reason.trim())} className={cn('rounded-lg px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50',active?'bg-rose-600':'bg-emerald-600')}>{saving?'Saving…':active?'Deactivate':'Reactivate'}</button></div></div>}
function Summary({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-3"><span className="text-neutral-500">{label}</span><span className="text-right font-semibold text-neutral-900">{value}</span></div>}
const fieldLabel='text-xs font-semibold text-neutral-600';
const inputClass='mt-1 min-h-11 w-full rounded-lg border border-neutral-300 bg-white px-3 text-sm';
const textareaClass='mt-1 w-full rounded-lg border border-neutral-300 px-3 py-2.5 text-sm';
