const PERMISSIONS = Object.freeze({
  AUTH_USER_CREATE: "auth.user.create.all",
  AUTH_USER_READ: "auth.user.read.all",
  AUTH_ROLE_MANAGE: "auth.role.manage.all",
  AUTH_PERMISSION_READ: "auth.permission.read.all",
  LEAD_CREATE_OWN: "lead.lead.create.own",
  LEAD_READ_OWN: "lead.lead.read.own",
  LEAD_READ_TEAM: "lead.lead.read.team",
  LEAD_READ_ALL: "lead.lead.read.all",
  LEAD_UPDATE_OWN: "lead.lead.update.own",
  LEAD_UPDATE_TEAM: "lead.lead.update.team",
  LEAD_UPDATE_ALL: "lead.lead.update.all",
  LEAD_DELETE_ALL: "lead.lead.delete.all",
  LEAD_ASSIGN_TEAM: "lead.lead.assign.team",
  LEAD_ASSIGN_ALL: "lead.lead.assign.all",
  LEAD_BULK_ASSIGN_ALL: "lead.lead.bulk_assign.all",
  LEAD_STATUS_CHANGE_OWN: "lead.status.change.own",
  LEAD_STATUS_CHANGE_TEAM: "lead.status.change.team",
  LEAD_STATUS_CHANGE_ALL: "lead.status.change.all",
  LEAD_FOLLOWUP_CREATE_OWN: "lead.followup.create.own",
  LEAD_FOLLOWUP_CREATE_ALL: "lead.followup.create.all",
  LEAD_MEETING_CREATE_OWN: "lead.meeting.create.own",
  LEAD_MEETING_CREATE_TEAM: "lead.meeting.create.team",
  LEAD_MEETING_CREATE_ALL: "lead.meeting.create.all",
  LEAD_MEETING_READ_OWN: "lead.meeting.read.own",
  LEAD_MEETING_READ_TEAM: "lead.meeting.read.team",
  LEAD_MEETING_READ_ALL: "lead.meeting.read.all",
  LEAD_MEETING_UPDATE_OWN: "lead.meeting.update.own",
  LEAD_MEETING_UPDATE_TEAM: "lead.meeting.update.team",
  LEAD_MEETING_UPDATE_ALL: "lead.meeting.update.all",
  LEAD_CONFIG_MANAGE: "lead.config.manage.all",
  LEAD_INTEGRATION_MANAGE: "lead.integration.manage",
});

const DEFAULT_OWNER_PERMISSIONS = Object.freeze(Object.values(PERMISSIONS));

export { DEFAULT_OWNER_PERMISSIONS, PERMISSIONS };
