import { useQuery } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Banknote, RefreshCw, RotateCcw, WalletCards } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { Skeleton } from '@/components/ui/Skeleton';
import { formatCurrency } from '@/lib/formatters';
import { cn } from '@/lib/cn';

const money=(value?:number)=>value==null?'—':formatCurrency(value);
const label=(value?:string)=>value?value.replace(/_/g,' '):'—';
export default function AdminWalletDetailPage(){
 const {doctorId}=useParams(); const nav=useNavigate();
 const q=useQuery<any>({queryKey:['admin-wallet-detail',doctorId],enabled:Boolean(doctorId),queryFn:()=>apiClient.get(`/admin/wallets/${doctorId}`).then(r=>r.data)});
 if(q.isLoading)return <div className="space-y-4">{Array.from({length:6}).map((_,i)=><Skeleton key={i} className="h-20 w-full"/>)}</div>;
 if(q.isError||!q.data)return <ErrorState title="Wallet could not load" message="The doctor wallet may not exist or the API is unavailable." onRetry={()=>q.refetch()}/>;
 const {doctor,wallet,recentTransactions,transactionCount}=q.data;
 return <div className="space-y-6"><header><button onClick={()=>nav('/admin/wallets')} className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-neutral-600"><ArrowLeft className="h-4 w-4"/>Wallets</button><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">Wallet ledger</p><h1 className="mt-2 text-2xl font-bold text-neutral-950">{doctor.fullName}</h1><p className="mt-1 text-sm text-neutral-500">{doctor.doctorId||'—'} · {doctor.clinicName||doctor.city||'—'} · {transactionCount} ledger entries</p></div><button onClick={()=>q.refetch()} className="inline-flex min-h-11 items-center gap-2 self-start rounded-lg border px-4 text-sm font-semibold"><RefreshCw className={cn('h-4 w-4',q.isFetching&&'animate-spin')}/>Refresh</button></div></header>
 <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-sm text-blue-900"><strong>Ledger rule:</strong> wallet balances are derived from financial events. This screen does not expose direct balance editing.</div>
 <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[WalletCards,'Available',wallet.availableBalance],[Banknote,'Pending',wallet.pendingBalance],[Banknote,'Withdrawal requested',wallet.withdrawalRequestedAmount],[RotateCcw,'Reversed',wallet.reversedBalance]].map(([I,l,v]:any)=><div key={l} className="rounded-xl border bg-white p-4"><I className="h-5 w-5 text-neutral-500"/><p className="mt-3 text-xs font-semibold uppercase text-neutral-500">{l}</p><p className="mt-1 text-xl font-bold">{money(v)}</p></div>)}</section>
 <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Doctor payout readiness</h2><div className="mt-4 grid gap-4 text-sm sm:grid-cols-3"><div><span className="text-xs font-semibold uppercase text-neutral-500">KYC</span><p className="mt-1 font-medium">{doctor.kycStatus||'—'}</p></div><div><span className="text-xs font-semibold uppercase text-neutral-500">Bank</span><p className="mt-1 font-medium">{doctor.bankVerified?'Verified':'Not verified'}</p></div><div><span className="text-xs font-semibold uppercase text-neutral-500">Payout cycle</span><p className="mt-1 font-medium">{doctor.payoutCycle||'—'}</p></div></div></section>
 <section className="overflow-hidden rounded-xl border bg-white"><div className="border-b px-5 py-4"><h2 className="font-bold">Recent ledger</h2><p className="mt-1 text-sm text-neutral-500">Latest credits, releases, withdrawals, payouts and reversals.</p></div>{recentTransactions?.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase text-neutral-500"><tr><th className="px-5 py-3">Date</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Balance change</th><th className="px-4 py-3">Payment</th><th className="px-5 py-3">Reason</th></tr></thead><tbody className="divide-y">{recentTransactions.map((t:any)=><tr key={t._id}><td className="px-5 py-4">{new Date(t.createdAt).toLocaleString()}</td><td className="px-4 py-4 font-medium">{label(t.type)}</td><td className="px-4 py-4 font-semibold">{money(t.amount)}</td><td className="px-4 py-4">{money(t.previousBalance)} → {money(t.newBalance)}</td><td className="px-4 py-4">{t.relatedPayment?.invoiceNumber||'—'}</td><td className="px-5 py-4 text-neutral-600">{t.reason||t.notes||'—'}</td></tr>)}</tbody></table></div>:<div className="p-10 text-center text-sm text-neutral-500">No wallet ledger entries yet.</div>}</section></div>
}