import { useDeferredValue, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Download, FileClock, RefreshCw, ShieldCheck, UserRoundCheck } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { SearchInput } from '@/components/ui/SearchInput';
import { Skeleton } from '@/components/ui/Skeleton';
import { cn } from '@/lib/cn';

type AuditLog={_id:string;action:string;module?:string;recordId?:string;reason?:string;userRole?:string;method?:string;path?:string;statusCode?:number;requestId?:string;createdAt:string;performedBy?:{email?:string;mobile?:string;role?:string;status?:string}};
type Response={items:AuditLog[];meta:{page:number;limit:number;total:number;totalPages:number};summary:{total:number;withReason:number;mutations:number;topRole?:string|null}};

export default function AdminAuditLogsPage(){
  const nav=useNavigate();
  const [search,setSearch]=useState(''); const dq=useDeferredValue(search.trim());
  const [module,setModule]=useState(''); const [role,setRole]=useState(''); const [method,setMethod]=useState(''); const [page,setPage]=useState(1);
  const q=useQuery<Response>({queryKey:['admin-audit-logs',page,dq,module,role,method],queryFn:()=>apiClient.get('/admin/audit-logs',{params:{page,limit:25,...(dq?{search:dq}:{}),...(module?{module}:{}),...(role?{userRole:role}:{}),...(method?{method}:{})}}).then(r=>r.data)});
  const s=q.data?.summary;
  const exportCsv=async()=>{const r=await apiClient.get('/admin/audit-logs/export',{params:{format:'csv',limit:5000,...(dq?{search:dq}:{}),...(module?{module}:{}),...(role?{userRole:role}:{}),...(method?{method}:{})},responseType:'blob'});const u=URL.createObjectURL(r.data);const a=document.createElement('a');a.href=u;a.download='audit-logs.csv';a.click();URL.revokeObjectURL(u)};
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">Governance</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">Audit Logs</h1><p className="mt-1 text-sm text-neutral-500">Immutable operational history for admin actions and sensitive workflow changes.</p></div><div className="flex gap-2"><button onClick={()=>q.refetch()} className="inline-flex min-h-11 items-center gap-2 rounded-lg border bg-white px-4 text-sm font-semibold"><RefreshCw className={cn('h-4 w-4',q.isFetching&&'animate-spin')}/>Refresh</button><button onClick={exportCsv} className="inline-flex min-h-11 items-center gap-2 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white"><Download className="h-4 w-4"/>Export CSV</button></div></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[FileClock,'Logs',s?.total],[ShieldCheck,'Mutating actions',s?.mutations],[UserRoundCheck,'With reason',s?.withReason],[UserRoundCheck,'Top actor role',s?.topRole||'—']].map(([I,l,v]:any)=><div key={l} className="rounded-xl border bg-white p-4"><I className="h-5 w-5 text-neutral-500"/><p className="mt-3 text-xs font-semibold uppercase text-neutral-500">{l}</p><p className="mt-1 text-2xl font-bold capitalize">{v??'—'}</p></div>)}</section>
  <section className="overflow-hidden rounded-xl border bg-white"><div className="grid gap-3 border-b p-4 lg:grid-cols-[1fr_180px_160px_150px]"><SearchInput value={search} onChange={v=>{setSearch(v);setPage(1)}} placeholder="Action, module, record ID, reason, request ID"/><input value={module} onChange={e=>{setModule(e.target.value);setPage(1)}} placeholder="Module" className="min-h-11 rounded-lg border px-3 text-sm"/><Filter value={role} onChange={v=>{setRole(v);setPage(1)}} label="All roles" options={['admin','doctor','agent','patient']}/><Filter value={method} onChange={v=>{setMethod(v);setPage(1)}} label="All methods" options={['GET','POST','PUT','PATCH','DELETE']}/></div>
  {q.isError?<div className="p-5"><ErrorState title="Audit logs could not load" message="Check the API and retry." onRetry={()=>q.refetch()}/></div>:q.isLoading?<div className="space-y-3 p-5">{Array.from({length:8}).map((_,i)=><Skeleton key={i} className="h-16"/>)}</div>:!q.data?.items.length?<div className="p-12 text-center text-sm text-neutral-500">No audit records match the current filters.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1150px] text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase text-neutral-500"><tr><th className="px-5 py-3">Actor</th><th className="px-4 py-3">Action</th><th className="px-4 py-3">Module / Record</th><th className="px-4 py-3">Request</th><th className="px-4 py-3">Time</th><th className="px-5 py-3 text-right">Action</th></tr></thead><tbody className="divide-y">{q.data.items.map(x=><tr key={x._id}><td className="px-5 py-4"><div className="font-semibold">{x.performedBy?.email||x.performedBy?.mobile||x.userRole||'System'}</div><div className="text-xs text-neutral-500 capitalize">{x.userRole||x.performedBy?.role||'system'}</div></td><td className="px-4 py-4"><div className="font-semibold">{x.action.replace(/_/g,' ')}</div>{x.reason&&<div className="mt-1 max-w-[280px] truncate text-xs text-neutral-500">{x.reason}</div>}</td><td className="px-4 py-4"><div>{x.module||'—'}</div><div className="text-xs text-neutral-500">{x.recordId||'—'}</div></td><td className="px-4 py-4"><span className="font-semibold">{x.method||'—'}</span><div className="max-w-[280px] truncate text-xs text-neutral-500">{x.path||x.requestId||'—'}</div></td><td className="px-4 py-4 text-neutral-600">{new Date(x.createdAt).toLocaleString()}</td><td className="px-5 py-4 text-right"><button onClick={()=>nav(`/admin/audit-logs/${x._id}`)} className="rounded-lg border px-3 py-2 text-xs font-semibold">View</button></td></tr>)}</tbody></table></div>}
  {q.data?.meta&&q.data.meta.totalPages>1&&<div className="flex items-center justify-between border-t px-4 py-3 text-sm"><span>Page {q.data.meta.page} of {q.data.meta.totalPages}</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Previous</button><button disabled={page>=q.data.meta.totalPages} onClick={()=>setPage(p=>p+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Next</button></div></div>}</section></div>}

function Filter({value,onChange,label,options}:{value:string;onChange:(v:string)=>void;label:string;options:string[]}){return <select value={value} onChange={e=>onChange(e.target.value)} className="min-h-11 rounded-lg border px-3 text-sm"><option value="">{label}</option>{options.map(x=><option key={x} value={x}>{x}</option>)}</select>}
