import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { AlertTriangle, ArrowLeft, CalendarDays, CheckCircle2, Clock3, ShieldAlert, Stethoscope, UserRound, XCircle } from 'lucide-react';
import apiClient from '@/lib/api-client';

type ProgramOption={_id:string;programCode?:string;name:string;durationDays?:number;difficultyLevel?:string;description?:string;defaultPrice?:number};
type Detail = {
  _id:string;
  patient?:{_id?:string;patientId?:string;fullName?:string;mobile?:string;status?:string;referringDoctor?:{fullName?:string;doctorId?:string;clinicName?:string}};
  caseType?:{name?:string;code?:string}; painCategory?:{_id?:string;name?:string}; surgeryType?:{name?:string;code?:string};
  surgeryDate?:string; side?:string; postOpDayAtAssessment?:number; requiresPhysioReview?:boolean;
  reviewType?:'red_flag'|'physio_review'; hasRedFlag?:boolean;
  redFlagDetails?:Array<{questionText?:string;answer?:unknown;reason?:string;safetyMessage?:string}>;
  approvedProgram?:ProgramOption|null; availablePrograms?:ProgramOption[];
  status:string; adminReviewNote?:string; reviewedBy?:{email?:string;mobile?:string}; reviewedAt?:string; createdAt:string;
};
const pretty=(v?:string)=>String(v||'—').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const showAnswer=(v:unknown)=>Array.isArray(v)?v.join(', '):typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'—');
const when=(v?:string)=>v?new Date(v).toLocaleString('en-IN'):'—';
const dateOnly=(v?:string)=>v?new Date(v).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—';

export default function AdminRiskReviewDetailPage(){
 const {reviewId}=useParams(); const navigate=useNavigate(); const qc=useQueryClient();
 const [decision,setDecision]=useState<'cleared'|'blocked'|null>(null); const [note,setNote]=useState(''); const [programId,setProgramId]=useState('');
 const query=useQuery({queryKey:['admin-risk-review',reviewId],enabled:!!reviewId,queryFn:async()=> (await apiClient.get<Detail>(`/admin/risk-reviews/${reviewId}`)).data});
 const mutation=useMutation({mutationFn:async()=> (await apiClient.patch(`/admin/risk-reviews/${reviewId}`,{status:decision,note:note.trim(),...(decision==='cleared'?{programId}: {})})).data,onSuccess:async()=>{setDecision(null);setNote('');setProgramId('');await Promise.all([qc.invalidateQueries({queryKey:['admin-risk-review',reviewId]}),qc.invalidateQueries({queryKey:['admin-risk-reviews']}),qc.invalidateQueries({queryKey:['admin-dashboard']})]);}});
 if(query.isLoading)return <div className="p-8 text-sm text-slate-500">Loading clinical review…</div>;
 if(query.isError||!query.data)return <div className="space-y-3"><button onClick={()=>navigate('/admin/risk-reviews')} className="text-sm font-semibold text-emerald-700">← Clinical Reviews</button><div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">Clinical review could not be loaded.</div></div>;
 const d=query.data; const pending=d.status==='pending_review'; const isRedFlag=d.reviewType==='red_flag'||Boolean(d.hasRedFlag); const postOpWeek=d.postOpDayAtAssessment===undefined?null:Math.floor(d.postOpDayAtAssessment/7)+1;
 const programs=d.availablePrograms||[]; const programmeMissing=d.status==='cleared'&&!d.approvedProgram?._id;
 const openDecision=(value:'cleared'|'blocked')=>{setDecision(value);setNote('');setProgramId(value==='cleared'?(d.approvedProgram?._id||''):'');};
 const submit=(e:FormEvent)=>{e.preventDefault();if(!decision||!note.trim())return;if(decision==='cleared'&&!programId)return;mutation.mutate();};
 return <div className="space-y-6">
  <button onClick={()=>navigate('/admin/risk-reviews')} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-900"><ArrowLeft size={16}/>Clinical Reviews</button>
  <header className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2">{isRedFlag?<AlertTriangle size={18} className="text-amber-600"/>:<Stethoscope size={18} className="text-sky-600"/>}<p className={`text-xs font-semibold tracking-[0.16em] ${isRedFlag?'text-amber-700':'text-sky-700'}`}>{isRedFlag?'RED-FLAG REVIEW':'PHYSIOTHERAPY REVIEW'}</p></div><h1 className="mt-2 text-2xl font-semibold text-slate-950">{d.patient?.fullName||'Patient clinical review'}</h1><p className="mt-1 text-sm text-slate-500">{d.patient?.patientId||d.patient?.mobile||'—'} · {d.caseType?.name||'Assessment'} · submitted {when(d.createdAt)}</p></div><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-semibold ${d.status==='blocked'?'bg-red-50 text-red-700':d.status==='cleared'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{pretty(d.status)}</span></header>

  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><main className="space-y-6">
   <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><CalendarDays size={18}/><h2 className="font-semibold text-slate-950">Clinical pathway</h2></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info label="Case type" value={d.caseType?.name||'Legacy assessment'}/><Info label="Body region" value={d.painCategory?.name||'—'}/><Info label="Surgery" value={d.surgeryType?.name||'Not applicable'}/><Info label="Side" value={pretty(d.side)}/><Info label="Surgery date" value={dateOnly(d.surgeryDate)}/><Info label="Post-op at assessment" value={d.postOpDayAtAssessment===undefined?'Not applicable':`Day ${d.postOpDayAtAssessment} · Week ${postOpWeek}`}/></dl></section>

   {isRedFlag ? <section className="rounded-2xl border border-amber-200 bg-amber-50/60 p-5"><div className="flex items-center gap-2"><ShieldAlert size={18} className="text-amber-700"/><h2 className="font-semibold text-slate-950">Triggered safety rules</h2></div><p className="mt-1 text-sm text-slate-600">Review the submitted answers that matched configured red-flag rules before allowing the programme to continue.</p><div className="mt-4 space-y-3">{(d.redFlagDetails||[]).map((flag,i)=><article key={i} className="rounded-xl border border-amber-200 bg-white p-4"><p className="font-medium text-slate-900">{flag.questionText||`Red flag ${i+1}`}</p><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><Info label="Patient answer" value={showAnswer(flag.answer)}/><Info label="Rule" value={pretty(flag.reason)}/></dl>{flag.safetyMessage&&<div className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800"><strong>Safety message:</strong> {flag.safetyMessage}</div>}</article>)}</div></section> : <section className="rounded-2xl border border-sky-200 bg-sky-50/60 p-5"><div className="flex items-center gap-2"><Clock3 size={18} className="text-sky-700"/><h2 className="font-semibold text-slate-950">Physio review required</h2></div><p className="mt-2 text-sm leading-6 text-slate-700">Review the case, surgery timing and patient context, then choose the rehabilitation programme before clearance.</p></section>}

   <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><UserRound size={18}/><h2 className="font-semibold text-slate-950">Patient & referral context</h2></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info label="Patient" value={d.patient?.fullName||'—'}/><Info label="Mobile" value={d.patient?.mobile||'—'}/><Info label="Referring doctor" value={d.patient?.referringDoctor?.fullName||'Direct PhysioQR patient'}/><Info label="Clinic" value={d.patient?.referringDoctor?.clinicName||'—'}/></dl>{d.patient?._id&&<button onClick={()=>navigate(`/admin/patients/${d.patient?._id}`)} className="mt-4 text-sm font-semibold text-emerald-700">Open patient workspace →</button>}</section>
  </main>

  <aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Clinical decision</h2>{pending?<><p className="mt-2 text-sm leading-6 text-slate-600">A review note is mandatory. Clearing also requires selecting an active programme mapped to this body region.</p>{!programs.length&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">No active programme is mapped to {d.painCategory?.name||'this body region'}. Create or map one in Admin → Programs before clearing.</div>}<div className="mt-4 grid gap-2"><button disabled={!programs.length} onClick={()=>openDecision('cleared')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50"><CheckCircle2 size={16}/>Clear & assign programme</button><button onClick={()=>openDecision('blocked')} className="inline-flex items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-semibold text-red-700"><XCircle size={16}/>Block assessment</button></div></>:<div className="mt-3 rounded-xl bg-slate-50 p-4 text-sm"><p><span className="text-slate-500">Decision:</span> <strong>{pretty(d.status)}</strong></p><p className="mt-2"><span className="text-slate-500">Programme:</span> <strong>{d.approvedProgram?.name||'Not assigned'}</strong></p><p className="mt-2"><span className="text-slate-500">Reviewed:</span> {when(d.reviewedAt)}</p><p className="mt-2"><span className="text-slate-500">Reviewer:</span> {d.reviewedBy?.email||d.reviewedBy?.mobile||'—'}</p><p className="mt-3 whitespace-pre-wrap text-slate-700">{d.adminReviewNote||'No review note recorded.'}</p></div>}{programmeMissing&&<><div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">This cleared review has no approved programme, so patient payment cannot continue.</div><button disabled={!programs.length} onClick={()=>openDecision('cleared')} className="mt-3 w-full rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Assign rehabilitation programme</button></>}</section></aside></div>

  {decision&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-xl"><h2 className="text-lg font-semibold text-slate-950">{decision==='cleared'?(pending?'Clear & assign programme':'Assign rehabilitation programme'):'Block assessment'}</h2><p className="mt-2 text-sm text-slate-600">This is an audited clinical decision. Record the reason and any relevant restrictions or follow-up.</p>{decision==='cleared'&&<label className="mt-4 block"><span className="text-sm font-semibold text-slate-700">Approved programme *</span><select value={programId} onChange={e=>setProgramId(e.target.value)} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500"><option value="">Select programme</option>{programs.map(program=><option key={program._id} value={program._id}>{program.name}{program.durationDays?` · ${program.durationDays} days`:''}</option>)}</select></label>}<textarea autoFocus={decision==='blocked'} value={note} onChange={e=>setNote(e.target.value)} rows={5} placeholder="Clinical review note" className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>{setDecision(null);setNote('');setProgramId('')}} className="rounded-xl border px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={!note.trim()||mutation.isPending||(decision==='cleared'&&!programId)} className={`rounded-xl px-4 py-2 text-sm font-semibold text-white disabled:opacity-50 ${decision==='blocked'?'bg-red-600':'bg-emerald-600'}`}>{mutation.isPending?'Saving…':'Confirm decision'}</button></div>{mutation.isError&&<p className="mt-3 text-sm text-red-700">{(mutation.error as any)?.response?.data?.message||'Decision could not be saved. Please retry.'}</p>}</form></div>}
 </div>;
}

function Info({label,value}:{label:string;value:unknown}){return <div><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-800">{String(value??'—')}</dd></div>}
