import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { AlertTriangle, ArrowLeft, CheckCircle2, ShieldAlert, UserRound, XCircle } from 'lucide-react';
import apiClient from '@/lib/api-client';

type Detail = { _id:string; patient?:{_id?:string;patientId?:string;fullName?:string;mobile?:string;status?:string;referringDoctor?:{fullName?:string;doctorId?:string;clinicName?:string}}; painCategory?:{name?:string}; redFlagDetails?:Array<{questionText?:string;answer?:unknown;reason?:string;safetyMessage?:string}>; status:string; adminReviewNote?:string; reviewedBy?:{email?:string}; reviewedAt?:string; createdAt:string };
const pretty=(v?:string)=>String(v||'—').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const showAnswer=(v:unknown)=>Array.isArray(v)?v.join(', '):typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'—');
const when=(v?:string)=>v?new Date(v).toLocaleString():'—';

export default function AdminRiskReviewDetailPage(){
 const {reviewId}=useParams(); const navigate=useNavigate(); const qc=useQueryClient(); const [decision,setDecision]=useState<'cleared'|'blocked'|null>(null); const [note,setNote]=useState('');
 const query=useQuery({queryKey:['admin-risk-review',reviewId],enabled:!!reviewId,queryFn:async()=> (await apiClient.get<Detail>(`/admin/risk-reviews/${reviewId}`)).data});
 const mutation=useMutation({mutationFn:async()=> (await apiClient.patch(`/admin/risk-reviews/${reviewId}`,{status:decision,note:note.trim()})).data,onSuccess:async()=>{setDecision(null);setNote('');await Promise.all([qc.invalidateQueries({queryKey:['admin-risk-review',reviewId]}),qc.invalidateQueries({queryKey:['admin-risk-reviews']}),qc.invalidateQueries({queryKey:['admin-dashboard']})]);}});
 if(query.isLoading)return <div className="p-8 text-sm text-slate-500">Loading clinical review…</div>;
 if(query.isError||!query.data)return <div className="space-y-3"><button onClick={()=>navigate('/admin/risk-reviews')} className="text-sm font-semibold text-emerald-700">← Risk reviews</button><div className="rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">Risk review could not be loaded.</div></div>;
 const d=query.data; const pending=d.status==='pending_review';
 const submit=(e:FormEvent)=>{e.preventDefault();if(decision&&note.trim())mutation.mutate();};
 return <div className="space-y-6"><button onClick={()=>navigate('/admin/risk-reviews')} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-900"><ArrowLeft size={16}/>Risk Reviews</button>
  <header className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><AlertTriangle size={18} className="text-amber-600"/><p className="text-xs font-semibold tracking-[0.16em] text-amber-700">RED-FLAG ASSESSMENT</p></div><h1 className="mt-2 text-2xl font-semibold text-slate-950">{d.patient?.fullName||'Patient risk review'}</h1><p className="mt-1 text-sm text-slate-500">{d.patient?.patientId||d.patient?.mobile||'—'} · {d.painCategory?.name||'Uncategorised'} · submitted {when(d.createdAt)}</p></div><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-semibold ${d.status==='blocked'?'bg-red-50 text-red-700':d.status==='cleared'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{pretty(d.status)}</span></header>
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><main className="space-y-6"><section className="rounded-2xl border border-amber-200 bg-amber-50/60 p-5"><div className="flex items-center gap-2"><ShieldAlert size={18} className="text-amber-700"/><h2 className="font-semibold text-slate-950">Triggered safety rules</h2></div><p className="mt-1 text-sm text-slate-600">Review the exact submitted answers that matched configured red-flag rules before making a decision.</p><div className="mt-4 space-y-3">{(d.redFlagDetails||[]).map((flag,i)=><article key={i} className="rounded-xl border border-amber-200 bg-white p-4"><p className="font-medium text-slate-900">{flag.questionText||`Red flag ${i+1}`}</p><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-500">Patient answer</dt><dd className="mt-1 font-medium text-slate-800">{showAnswer(flag.answer)}</dd></div><div><dt className="text-xs text-slate-500">Rule</dt><dd className="mt-1 text-slate-700">{pretty(flag.reason)}</dd></div></dl>{flag.safetyMessage&&<div className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800"><strong>Safety message:</strong> {flag.safetyMessage}</div>}</article>)}</div></section>
   <section className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center gap-2"><UserRound size={18}/><h2 className="font-semibold text-slate-950">Patient & referral context</h2></div><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Patient</dt><dd className="mt-1 font-medium">{d.patient?.fullName||'—'}</dd></div><div><dt className="text-slate-500">Mobile</dt><dd className="mt-1">{d.patient?.mobile||'—'}</dd></div><div><dt className="text-slate-500">Referring doctor</dt><dd className="mt-1">{d.patient?.referringDoctor?.fullName||'—'}</dd></div><div><dt className="text-slate-500">Clinic</dt><dd className="mt-1">{d.patient?.referringDoctor?.clinicName||'—'}</dd></div></dl>{d.patient?._id&&<button onClick={()=>navigate(`/admin/patients/${d.patient?._id}`)} className="mt-4 text-sm font-semibold text-emerald-700">Open patient workspace →</button>}</section>
  </main><aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-semibold text-slate-950">Clinical decision</h2>{pending?<><p className="mt-2 text-sm text-slate-600">A review note is mandatory. Clear only when the red flag has been reviewed and it is safe to proceed; otherwise block the assessment.</p><div className="mt-4 grid gap-2"><button onClick={()=>setDecision('cleared')} className="inline-flex items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"><CheckCircle2 size={16}/>Clear red flag</button><button onClick={()=>setDecision('blocked')} className="inline-flex items-center justify-center gap-2 rounded-xl border border-red-200 bg-red-50 px-4 py-2.5 text-sm font-semibold text-red-700"><XCircle size={16}/>Block assessment</button></div></>:<div className="mt-3 rounded-xl bg-slate-50 p-4 text-sm"><p><span className="text-slate-500">Decision:</span> <strong>{pretty(d.status)}</strong></p><p className="mt-2"><span className="text-slate-500">Reviewed:</span> {when(d.reviewedAt)}</p><p className="mt-2"><span className="text-slate-500">Reviewer:</span> {d.reviewedBy?.email||'—'}</p><p className="mt-3 whitespace-pre-wrap text-slate-700">{d.adminReviewNote||'No review note recorded.'}</p></div>}</section></aside></div>
  {decision&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-5 shadow-xl"><h2 className="text-lg font-semibold text-slate-950">{decision==='cleared'?'Clear red flag':'Block assessment'}</h2><p className="mt-2 text-sm text-slate-600">This is an audited clinical-safety decision. Record the reason and any relevant follow-up.</p><textarea autoFocus value={note} onChange={e=>setNote(e.target.value)} rows={5} placeholder="Clinical review note" className="mt-4 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>{setDecision(null);setNote('')}} className="rounded-xl border px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={!note.trim()||mutation.isPending} className={`rounded-xl px-4 py-2 text-sm font-semibold text-white disabled:opacity-50 ${decision==='blocked'?'bg-red-600':'bg-emerald-600'}`}>{mutation.isPending?'Saving…':'Confirm decision'}</button></div>{mutation.isError&&<p className="mt-3 text-sm text-red-700">Decision could not be saved. Please review the note and retry.</p>}</form></div>}
 </div>;
}
