import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, RefreshCw, ShieldAlert } from 'lucide-react';
import apiClient from '@/lib/api-client';
import ErrorState from '@/components/feedback/ErrorState';
import { Skeleton } from '@/components/ui/Skeleton';
import { Modal } from '@/components/ui/Modal';
import { cn } from '@/lib/cn';
import { formatCurrency } from '@/lib/formatters';

const label=(value?:string)=>value?value.replace(/_/g,' '):'—';

export default function AdminFraudRiskDetailPage(){
  const { fraudCaseId }=useParams(); const nav=useNavigate(); const qc=useQueryClient();
  const [reviewOpen,setReviewOpen]=useState(false); const [reviewStatus,setReviewStatus]=useState('reviewing'); const [note,setNote]=useState(''); const [formError,setFormError]=useState('');
  const q=useQuery<any>({queryKey:['admin-fraud-case',fraudCaseId],enabled:Boolean(fraudCaseId),queryFn:()=>apiClient.get(`/admin/fraud-cases/${fraudCaseId}`).then(r=>r.data)});
  const review=useMutation({mutationFn:()=>apiClient.patch(`/admin/fraud-cases/${fraudCaseId}/review`,{status:reviewStatus,note}),onSuccess:()=>{setReviewOpen(false);setNote('');setFormError('');qc.invalidateQueries({queryKey:['admin-fraud-case',fraudCaseId]});qc.invalidateQueries({queryKey:['admin-fraud-risk']})},onError:(e:any)=>setFormError(e?.response?.data?.message||'Review could not be saved.')});
  if(q.isLoading)return <div className="space-y-3">{Array.from({length:7}).map((_,i)=><Skeleton key={i} className="h-20"/>)}</div>;
  if(q.isError||!q.data?.fraudCase)return <ErrorState title="Fraud case could not load" message="The case may not exist or the API is unavailable." onRetry={()=>q.refetch()}/>;
  const f=q.data.fraudCase;
  return <div className="space-y-6">
    <header><button onClick={()=>nav('/admin/fraud-risk')} className="mb-3 inline-flex items-center gap-2 text-sm font-semibold text-neutral-600"><ArrowLeft className="h-4 w-4"/>Fraud Risk</button><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-primary-700">Fraud case</p><h1 className="mt-2 text-2xl font-bold sm:text-3xl">{label(f.rule)}</h1><p className="mt-1 text-sm text-neutral-500">Created {new Date(f.createdAt).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={()=>q.refetch()} className="inline-flex min-h-11 items-center gap-2 rounded-lg border px-4 text-sm font-semibold"><RefreshCw className={cn('h-4 w-4',q.isFetching&&'animate-spin')}/>Refresh</button>{!['resolved','dismissed'].includes(f.status)&&<button onClick={()=>{setReviewStatus(f.status==='open'?'reviewing':f.status);setReviewOpen(true)}} className="min-h-11 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white">Review case</button>}</div></div></header>
    <section className="grid gap-3 sm:grid-cols-3"><Card title="Severity" value={f.severity}/><Card title="Status" value={label(f.status)}/><Card title="Related record" value={f.relatedRecord||'—'}/></section>
    <section className="rounded-xl border bg-white p-5"><div className="flex items-center gap-2"><ShieldAlert className="h-5 w-5 text-neutral-500"/><h2 className="font-bold">Case summary</h2></div><p className="mt-3 text-sm leading-6 text-neutral-700">{f.summary||'No summary recorded.'}</p></section>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Linked entities</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info label="Doctor" value={f.doctor?.fullName}/><Info label="Doctor ID" value={f.doctor?.doctorId}/><Info label="Clinic" value={f.doctor?.clinicName}/><Info label="Doctor status" value={f.doctor?.status}/><Info label="Patient" value={f.patient?.fullName}/><Info label="Patient ID" value={f.patient?.patientId}/><Info label="Patient status" value={f.patient?.status}/><Info label="Referral locked" value={f.patient?.referralLocked==null?'—':f.patient.referralLocked?'Yes':'No'}/></dl></section><section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Payment context</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Info label="Invoice" value={f.payment?.invoiceNumber}/><Info label="Amount" value={f.payment?.paidAmount!=null?formatCurrency(f.payment.paidAmount):'—'}/><Info label="Refund amount" value={f.payment?.refundAmount!=null?formatCurrency(f.payment.refundAmount):'—'}/><Info label="Payment status" value={f.payment?.status}/><Info label="Gateway" value={f.payment?.gatewayProvider}/><Info label="Transaction ID" value={f.payment?.gatewayTransactionId}/><Info label="Payment method" value={f.payment?.paymentMethod}/><Info label="Verified at" value={f.payment?.verifiedAt?new Date(f.payment.verifiedAt).toLocaleString():'—'}/></dl></section></div>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Evidence</h2><pre className="mt-4 overflow-x-auto whitespace-pre-wrap rounded-lg bg-neutral-50 p-4 text-xs leading-5 text-neutral-700">{f.evidence?JSON.stringify(f.evidence,null,2):'No structured evidence recorded.'}</pre></section>
    <section className="rounded-xl border bg-white p-5"><h2 className="font-bold">Review trail</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-3"><Info label="Reviewed by" value={f.reviewedBy?.email||f.reviewedBy?.mobile}/><Info label="Reviewed at" value={f.reviewedAt?new Date(f.reviewedAt).toLocaleString():'—'}/><Info label="Resolution note" value={f.resolutionNote}/></dl></section>
    <Modal isOpen={reviewOpen} onClose={()=>{setReviewOpen(false);setFormError('')}} title="Review fraud case"><div className="space-y-4 pt-5">{formError&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{formError}</div>}<label className="block"><span className="text-xs font-semibold text-neutral-600">Decision</span><select value={reviewStatus} onChange={e=>setReviewStatus(e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border px-3 text-sm"><option value="reviewing">Reviewing</option><option value="resolved">Resolved</option><option value="dismissed">Dismissed</option></select></label><label className="block"><span className="text-xs font-semibold text-neutral-600">Review note</span><textarea value={note} onChange={e=>setNote(e.target.value)} rows={5} maxLength={2000} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" placeholder="Record why this decision was made."/></label><div className="rounded-lg border bg-neutral-50 p-3 text-xs text-neutral-600">This action updates the fraud case review state and writes an audit log. It does not automatically block a doctor, patient, payment or wallet.</div><div className="flex justify-end gap-2"><button onClick={()=>setReviewOpen(false)} className="min-h-11 rounded-lg border px-4 text-sm font-semibold">Cancel</button><button disabled={review.isPending||!note.trim()} onClick={()=>review.mutate()} className="min-h-11 rounded-lg bg-primary-600 px-4 text-sm font-semibold text-white">{review.isPending?'Saving…':'Save review'}</button></div></div></Modal>
  </div>
}
function Card({title,value}:{title:string;value:any}){return <div className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase text-neutral-500">{title}</p><p className="mt-2 text-xl font-bold capitalize">{value??'—'}</p></div>}
function Info({label:heading,value}:{label:string;value:any}){return <div><dt className="text-xs font-semibold uppercase text-neutral-500">{heading}</dt><dd className="mt-1 font-medium break-words">{value||'—'}</dd></div>}